#!/bin/bash

function chmod-web-recursive() {
  if [ $# == 1 ]; then
    for i in `find $1 -type d`; do chmod 755 $i; done
    for i in `find $1 -type f`; do chmod 644 $i; done
  else
    echo ""
    echo "  Chmod a root folder and all children to web ready permissions."
    echo ""
    echo "  chmod-web-recursive [root folder]"
    echo ""
  fi
}
