#!/bin/bash

function speak() {
  echo ""
  echo "$1"
  echo ""
}

function update_php() {
  brew unlink php`php -r "echo substr(str_replace('.', '', phpversion()), 0, 2);"`
  brew upgrade php$1
}

function good() {
  if [ "$1" == "morning" ]; then
    speak "GOOD MORNING YOU ASSHOLE!"

    brew update

    VERSION=`php -r "echo substr(str_replace('.', '', phpversion()), 0, 2);"`

    update_php 56
    update_php 70

    brew upgrade
    brew cleanup
    brew doctor

    npm update npm -g
    npm update -g

    sudo gem update --system
    sudo gem update

    sudo composer selfupdate
  elif [ "$1" == "night" ]; then
    speak "NO! Your face is a good night!"
    diskutil repairPermissions /
  fi
}
