#!/bin/bash

function good() {
  if [ "$1" == "morning" ]; then
    echo ""
    echo "GOOD MORNING YOU ASSHOLE!"
    echo ""

    brew update
    brew upgrade
    brew cleanup
    brew doctor

    # upgrade all the installed php versions
    brew unlink php56
    brew link php55
    brew upgrade
    brew unlink php55
    brew link php54
    brew upgrade
    brew unlink php54
    brew link php53
    brew upgrade
    brew unlink php53
    brew link php56

    sudo npm update npm -g
    sudo npm update -g

    sudo gem update --system
    sudo gem update

    sudo composer selfupdate
  elif [ "$1" == "night" ]; then
    echo ""
    echo "NO! Your face is a good night!"
    echo ""
    diskutil repairPermissions /
  fi
}
