#!/bin/bash

function good() {
  if [ "$1" == "morning" ]; then
    echo ""
    echo "GOOD MORNING YOU ASSHOLE!"
    echo ""

    brew update
    brew upgrade
    brew cleanup
    brew doctor

    sudo npm update npm -g
    sudo npm update -g

    sudo gem update --system
    sudo gem update

    sudo composer selfupdate
  elif [ "$1" == "night" ]; then
    echo ""
    echo "NO! Your face is a good night!"
    echo ""
    diskutil repairPermissions /
  fi
}
