#!/bin/bash

function ssh-key-copy() {
  if [ $# == 2 ]; then
    cat ~/.ssh/id_rsa.pub | ssh $1 "mkdir ~/.ssh ; cat - >> ~/.ssh/authorized_keys"
  elif [ $# == 1 ]; then
    cat $1 | ssh $2 "mkdir ~/.ssh; cat - >> ~/.ssh/authorized_keys"
  else
    echo ""
    echo "  Copy your ssh key to the authorized_keys file on a remote server."
    echo ""
    echo "  ssh-key-copy [user@address]           - copies ~/.ssh/id_rsa.pub to a remote server"
    echo "  ssh-key-copy [keyfile] [user@address] - copies the file you specify to a remote server"
    echo ""
  fi
}
