#!/bin/bash

# link files
for file in $(find ~/.settings/config -type f)
do
  if [ ! -f ~/$(basename $file) ]; then
    ln -s $file ~
  fi
done

# link executables
if [ ! -d ~/bin ]; then
  mkdir -p ~/bin
fi

for file in $(find ~/.settings/bin -type f)
do
  if [ ! -f ~/bin/$(basename $file) ]; then
    ln -s $file ~/bin
  fi
done

if [ ! -f ~/.profile ] && [ ! -f ~/.zprofile ]; then
  if test -n "$ZSH_VERSION"; then
    ln -s ~/.settings/profile ~/.zprofile
    source ~/.zprofile
    echo "Installing for ZSH"
  else
    ln -s ~/.settings/profile ~/.profile
    source ~/.profile
    echo "Installing for BASH"
  fi
fi
