#!/bin/bash

if [ -n "$ZSH_VERSION" ]; then
  echo "Installing for ZSH"
elif [ -n "$BASH_VERSION" ]; then
  echo "Installing for BASH"
else
  echo "Could not determine shell.  Make sure to run using 'source'"
  exit 0
fi

# link files
for file in $(find ~/.settings/config -type f)
do
  if [ ! -f ~/$(basename $file) ]; then
    ln -s $file ~
    echo "$file linked"
  else
    echo "$file exists"
  fi
done

# link executables
if [ ! -d ~/bin ]; then
  mkdir -p ~/bin
  echo "~/bin folder created"
else
  echo "~/bin folder exists"
fi

for file in $(find ~/.settings/bin -type f)
do
  if [ ! -f ~/bin/$(basename $file) ]; then
    ln -s $file ~/bin
    echo "$file linked"
  else
    echo "$file exists"
  fi
done

if [ -n "$ZSH_VERSION" ]; then
  if [ ! -f ~/.zshrc ]; then
    # ln -s ~/.settings/profile ~/.zprofile
    ln -s ~/.settings/zshrc ~/.zshrc
    source ~/.zshrc
    # echo "~/.zprofile linked"
    echo "~/.zshrc linked"
  else
    echo "~/.zshrc exists"
  fi
else
  if [ ! -f ~/.profile ]; then
    ln -s ~/.settings/profile ~/.profile
    source ~/.profile
    echo "~/.profile linked"
  else
    echo "~/.profile exists"
  fi
fi

echo "Installing brew ..."
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install git nvm z httpie httpstat speedtest-cli